<script setup>
import { ref } from "vue";
import "./styles.css";
import Icon from "./Icon.js";
const props = defineProps({ items: { type: Array, default: () => [] }, groups: { type: Array, default: () => [] }, selected: String, ariaLabel: { type: String, default: "主导航" } });
const emit = defineEmits(["select"]);
const expandedGroups = ref({});
const groupExpanded = (group, index) => expandedGroups.value[index] ?? group.expanded !== false;
const toggleGroup = (index) => { expandedGroups.value[index] = !groupExpanded(props.groups[index], index); };
</script>
<template>
  <nav v-if="!$slots.default && groups.length > 1" class="tui-component tui-sidebar-groups" data-component="sidebar-groups" data-logical-component="Sidebar Groups/Default" data-framework="vue" :aria-label="ariaLabel">
    <section v-for="(group, index) in groups" :key="group.id || index" class="tui-component tui-disclosure tui-sidebar-group" data-component="collapsible" data-renderer-key="collapsible" data-logical-component="Collapsible/Default" :data-variant="groupExpanded(group, index) ? 'open' : 'default'" :data-state="groupExpanded(group, index) ? 'open' : 'default'" data-framework="vue">
      <button class="tui-disclosure__trigger tui-sidebar-group__trigger" type="button" :aria-expanded="groupExpanded(group, index)" :aria-controls="`sidebar-group-content-${index + 1}`" data-typography-role="subtitle-s" @click="toggleGroup(index)"><span data-slot="label">{{ group.label || `导航组 ${index + 1}` }}</span><Icon name="navigation/chevron-down" :size="16" /></button>
      <div class="tui-disclosure__content tui-sidebar-group__content" :id="`sidebar-group-content-${index + 1}`" data-slot="content" :hidden="!groupExpanded(group, index)"><nav class="tui-component tui-sidebar" data-component="sidebar" data-logical-component="Sidebar Item/Default" data-variant="default" data-state="default" data-framework="vue" :aria-label="group.ariaLabel || group.label || ariaLabel"><button v-for="item in group.items || []" :key="item.id || item.label" class="tui-sidebar-item" type="button" data-component="sidebar-item" data-renderer-key="sidebar-item" data-logical-component="Sidebar Item/Default" :data-variant="item.id === selected ? 'selected' : item.state || 'default'" :data-state="item.id === selected ? 'selected' : item.state || 'default'" data-framework="vue" :disabled="item.disabled || item.state === 'disabled'" @click="emit('select', item.id)"><span data-slot="leading"><Icon :name="item.iconAlias || item.icon || 'navigation/grid'" :size="20" /></span><span data-slot="label" data-typography-role="body-l">{{ item.label }}</span><span v-if="item.count !== undefined" class="tui-sidebar-item__count" data-slot="trailing" data-typography-role="body-m">{{ item.count }}</span></button></nav></div>
    </section>
  </nav>
  <nav v-else class="tui-component tui-sidebar" data-component="sidebar" data-logical-component="Sidebar Item/Default" data-variant="default" data-state="default" data-framework="vue" :aria-label="ariaLabel"><slot><button v-for="item in (groups.length === 1 ? groups[0].items || [] : items)" :key="item.id || item.label" class="tui-sidebar-item" type="button" data-component="sidebar-item" data-renderer-key="sidebar-item" data-logical-component="Sidebar Item/Default" :data-variant="item.id === selected ? 'selected' : item.state || 'default'" :data-state="item.id === selected ? 'selected' : item.state || 'default'" data-framework="vue" :disabled="item.disabled || item.state === 'disabled'" @click="emit('select', item.id)"><span data-slot="leading"><Icon :name="item.iconAlias || item.icon || 'navigation/grid'" :size="20" /></span><span data-slot="label" data-typography-role="body-l">{{ item.label }}</span><span v-if="item.count !== undefined" class="tui-sidebar-item__count" data-slot="trailing" data-typography-role="body-m">{{ item.count }}</span></button></slot></nav>
</template>
