// Independent HTML adapters for the remaining contract components.
// These are intentionally not generated Menu/Picker snapshots: every
// adapter owns its semantic DOM and the small amount of behavior it needs.
import { iconMarkup } from "./icon-map.js";

const escapeHtml = (value = "") => String(value)
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;")
  .replaceAll("'", "&#39;");

const icon = (name, size = 20, kind = "auto") => iconMarkup(name, { size, kind });
const attrs = (id, logicalName, variant = "default", state = "default", extra = "") =>
  `data-component="${id}" data-renderer-key="${id}" data-logical-component="${logicalName}" data-variant="${variant}" data-state="${state}" data-framework="html"${extra}`;
const slot = (value, fallback = "") => value === undefined || value === null ? fallback : String(value);
const defaultMenubarItems = [{ label: "新建", icon: "action/add" }, { label: "打开", icon: "action/download", hasSubmenu: true, submenu: ["打开项目", "打开最近项目", "从设备打开"] }, { label: "导出", icon: "action/settings" }];

const menu = (items) => items.map((item) => {
  const entry = typeof item === "string" ? { label: item } : item;
  const leading = entry.icon
    ? `<span class="tui-advanced-menu__item-leading" data-slot="leading">${icon(entry.icon, 24)}</span>`
    : "";
  const trailing = entry.hasSubmenu
    ? `<span class="tui-advanced-menu__item-trailing" data-slot="trailing">${icon("navigation/chevron-right", 24)}</span>`
    : "";
  const submenu = entry.hasSubmenu && Array.isArray(entry.submenu)
    ? `<div class="tui-advanced-menu__submenu" role="menu" aria-label="${escapeHtml(entry.label)}" hidden>${menu(entry.submenu)}</div>`
    : "";
  return `<div class="tui-advanced-menu__item-wrap${entry.hasSubmenu ? " has-submenu" : ""}"><button type="button" role="menuitem" class="tui-advanced-menu__item${entry.hasSubmenu ? " has-submenu" : ""}" data-typography-role="body-l"${entry.hasSubmenu ? " aria-haspopup=\"menu\" aria-expanded=\"false\"" : ""}>${leading}<span data-slot="label">${escapeHtml(entry.label)}</span>${trailing}</button>${submenu}</div>`;
}).join("");
const openOverlayHandler = `const l=this.nextElementSibling;l.hidden=false;const d=l.querySelector('.tui-dialog');d.dataset.state='open';d.focus()`;
const closeOverlayHandler = `const e=this.closest('[data-overlay-example]');this.closest('.tui-overlay-layer').hidden=true;e.querySelector('[data-overlay-trigger]').focus()`;
const escapeOverlayHandler = `if(event.key==='Escape'){event.preventDefault();const e=this.closest('[data-overlay-example]');this.closest('.tui-overlay-layer').hidden=true;e.querySelector('[data-overlay-trigger]').focus()}`;

const overlayLayer = ({ id, componentId = id, triggerLabel, role = "dialog", title, subtitle = "", description, modifier = "", actions, actionSlot = "", titlebarSlot = "", content = "", extra = "" }) => {
  const titleId = `${id}-title`;
  const descriptionId = `${id}-description`;
  const titlebar = titlebarSlot || `<h4 id="${titleId}" data-slot="title" data-typography-role="title-s">${escapeHtml(title)}</h4>${subtitle ? `<p data-slot="subtitle" data-typography-role="body-m">${escapeHtml(subtitle)}</p>` : ""}`;
  const defaultActions = actions.map((action) => `<button class="tui-button" type="button" data-variant="${action.variant}" data-overlay-action="${action.action}" data-typography-role="body-l" onclick="${closeOverlayHandler}">${escapeHtml(action.label)}</button>`).join("");
  return `<div class="tui-overlay-example" data-overlay-example="${id}">
    <button class="tui-button" type="button" data-variant="secondary" data-overlay-trigger="${id}" data-typography-role="body-l" onclick="${openOverlayHandler}">${escapeHtml(triggerLabel)}</button>
    <div class="tui-overlay-layer" id="${id}" data-overlay-id="${id}" hidden${extra}>
      <div class="tui-overlay-backdrop" aria-hidden="true"></div>
      <section class="tui-component tui-dialog ${modifier}" ${attrs(componentId, `${componentId === "alert-dialog" ? "Alert Dialog" : componentId === "semi-modal" ? "Semi-modal" : "Dialog"}/Default`, componentId === "dialog" ? actions.length === 1 ? "single" : actions.length === 3 ? "triple" : "double" : "white", "open")} role="${role}" aria-modal="true" aria-labelledby="${titleId}" aria-describedby="${descriptionId}" tabindex="-1" onkeydown="${escapeOverlayHandler}">
        <header class="tui-dialog__header" data-slot="titlebar">${titlebar}${componentId === "semi-modal" ? `<button class="tui-icon-button tui-dialog__close" type="button" data-overlay-close aria-label="关闭">${icon("action/close", 20)}</button>` : ""}</header>
        <div class="tui-dialog__content"><p id="${descriptionId}" data-slot="description" data-typography-role="body-m">${escapeHtml(description)}</p>${content}</div>
        <footer class="tui-dialog__actions" data-slot="actions" data-action-layout="${actions.length === 1 ? "single" : actions.length === 3 ? "triple" : "double"}">${actionSlot || defaultActions}</footer>
      </section>
    </div>
  </div>`;
};

export const dialog = () => `<div class="tui-overlay-specimens" data-component="dialog">${overlayLayer({ id: "dialog-single", componentId: "dialog", triggerLabel: "打开单按钮对话弹窗", title: "更新完成", description: "应用已经更新到最新版本。", actions: [{ action: "confirm", variant: "primary", label: "知道了" }] })}${overlayLayer({ id: "dialog-double", componentId: "dialog", triggerLabel: "打开双按钮对话弹窗", title: "确认更新？", description: "更新期间应用需要重新启动。", actions: [{ action: "cancel", variant: "secondary", label: "取消" }, { action: "confirm", variant: "primary", label: "确认" }] })}${overlayLayer({ id: "dialog-triple", componentId: "dialog", triggerLabel: "打开三按钮对话弹窗", title: "保存更改？", description: "你可以先保存草稿，稍后再继续编辑。", actions: [{ action: "confirm", variant: "primary", label: "确认" }, { action: "third", variant: "secondary", label: "保存草稿" }, { action: "cancel", variant: "secondary", label: "取消" }] })}</div>`;

export const alertDialog = () => overlayLayer({ id: "alert-dialog", triggerLabel: "打开删除确认弹窗", role: "alertdialog", title: "删除项目？", description: "删除后无法恢复，请确认操作。", modifier: "tui-dialog--alert", actions: [{ action: "cancel", variant: "secondary", label: "取消" }, { action: "confirm", variant: "danger", label: "删除" }] });

export const semiModal = () => {
  const fields = `<div class="tui-dialog__form"><label class="tui-field"><span data-typography-role="body-m">项目名称</span><span class="tui-input" data-field-control data-surface="white"><input type="text" value="客户端设计系统" data-typography-role="body-l" /></span></label><label class="tui-field"><span data-typography-role="body-m">负责人</span><span class="tui-search" data-field-control data-surface="white">${icon("field/search", 20)}<input type="search" value="赵博海" data-typography-role="body-l" /></span></label></div>`;
  const axisHandler = (axis) => `const l=this.closest('[data-overlay-example]').querySelector('[data-overlay-id=semi-modal]');l.dataset.${axis}=this.value;const d=l.querySelector('.tui-dialog');d.dataset.variant=l.dataset.size+'-'+l.dataset.surface+'-'+l.dataset.mode;d.setAttribute('aria-modal',String(l.dataset.mode==='modal'))`;
  const controls = `<div class="tui-specimen-controls" aria-label="半模态结构维度"><label data-typography-role="body-m">尺寸<select data-semi-axis="size" onchange="${axisHandler("size")}"><option value="s">S · 480</option><option value="m" selected>M · 640</option><option value="l">L · 800</option></select></label><label data-typography-role="body-m">背景<select data-semi-axis="surface" onchange="${axisHandler("surface")}"><option value="white" selected>White</option><option value="gray">Gray</option></select></label><label data-typography-role="body-m">模式<select data-semi-axis="mode" onchange="${axisHandler("mode")}"><option value="non-modal" selected>Non-modal</option><option value="modal">Modal</option></select></label></div>`;
  return `<div class="tui-overlay-example" data-overlay-example="semi-modal">${controls}<button class="tui-button" type="button" data-variant="secondary" data-overlay-trigger="semi-modal" data-typography-role="body-l" onclick="const l=this.nextElementSibling;l.hidden=false;const d=l.querySelector('.tui-dialog');d.dataset.state='open';d.focus()">打开半模态弹窗</button><div class="tui-overlay-layer" id="semi-modal" data-overlay-id="semi-modal" data-size="m" data-surface="white" data-mode="non-modal" hidden><div class="tui-overlay-backdrop" aria-hidden="true"></div><section class="tui-component tui-dialog tui-dialog--semi" ${attrs("semi-modal", "Semi-modal/Default", "m-white-non-modal", "open")} role="dialog" aria-modal="false" aria-labelledby="semi-modal-title" aria-describedby="semi-modal-description" tabindex="-1" onkeydown="${escapeOverlayHandler}"><header class="tui-dialog__header"><h4 id="semi-modal-title" data-typography-role="title-s">编辑项目设置</h4><button class="tui-icon-button tui-dialog__close" type="button" data-overlay-close aria-label="关闭" onclick="${closeOverlayHandler}">${icon("action/close", 20)}</button></header><div class="tui-dialog__content"><p id="semi-modal-description" data-typography-role="body-m">非模态为默认状态，可以继续操作背景内容。</p>${fields}</div><footer class="tui-dialog__actions" data-action-layout="double"><button class="tui-button" type="button" data-variant="secondary" data-overlay-action="cancel" data-typography-role="body-l" onclick="${closeOverlayHandler}">取消</button><button class="tui-button" type="button" data-variant="primary" data-overlay-action="confirm" data-typography-role="body-l" onclick="${closeOverlayHandler}">保存</button></footer></section></div></div>`;
};

const menuComponent = (id, logicalName, label, value, items) => `<div class="tui-component tui-advanced-menu" ${attrs(id, logicalName, "default", "default")}><span class="tui-advanced-menu__label" data-typography-role="body-m">${escapeHtml(label)}</span><button class="tui-advanced-menu__trigger" type="button" aria-haspopup="menu" aria-expanded="false"><span data-slot="value" data-typography-role="body-l">${escapeHtml(value)}</span>${icon("navigation/chevron-down", 16)}</button><div class="tui-advanced-menu__panel" role="menu" hidden>${menu(items)}</div></div>`;
export const menubar = ({ items = defaultMenubarItems } = {}) => `<nav class="tui-component tui-advanced-menubar" ${attrs("menubar", "Menubar/Default")} aria-label="主菜单"><button class="tui-advanced-menu__trigger" type="button" aria-haspopup="menu" aria-expanded="false" data-typography-role="body-l">文件 ${icon("navigation/chevron-down", 16)}</button><div class="tui-advanced-menu__panel" role="menu" hidden>${menu(items)}</div></nav>`;
export const contextMenu = () => menuComponent("context-menu", "Context Menu/Default", "更多操作", "右键或点击打开", [{ label: "复制", icon: "action/copy" }, { label: "重命名", icon: "action/rename" }, { label: "删除", icon: "action/delete" }]);
export const dropdownMenu = () => menuComponent("dropdown-menu", "Dropdown Menu/Default", "操作菜单", "新建、导入、导出", ["新建", "导入", "导出"]);

export const popover = () => `<div class="tui-component tui-advanced-popover" ${attrs("popover", "Popover/Default")}><button class="tui-button" type="button" data-variant="ghost" data-typography-role="body-l" aria-expanded="false">筛选条件</button><div class="tui-advanced-popover__panel" role="dialog" hidden><strong data-typography-role="title-s">筛选条件</strong><span data-typography-role="body-m">状态、负责人、更新时间</span></div></div>`;
export const hoverCard = () => `<div class="tui-component tui-advanced-hover-card" ${attrs("hover-card", "Hover Card/Default")}><button class="tui-button" type="button" data-variant="ghost" data-typography-role="body-l">组件说明</button><div class="tui-advanced-hover-card__panel" role="tooltip"><strong data-typography-role="title-s">组件说明</strong><span data-typography-role="body-m">查看组件的详细使用规则</span></div></div>`;

const sliderState = ({ variant = "style-1", label = "透明度", value = 84 } = {}) => {
  const style = variant === "style-2" ? "style-2" : "style-1";
  const numericValue = Number(value);
  const normalizedValue = Number.isFinite(numericValue) ? Math.min(100, Math.max(0, numericValue)) : 84;
  return `<label class="tui-component tui-slider tui-slider--${style}" ${attrs("slider", "Slider/Default", style, "default", ` data-slider-style="${style}"`)}><span data-slot="label" data-typography-role="body-m">${escapeHtml(label)}</span><span class="tui-slider__control" style="--tui-slider-value:${normalizedValue}%"><span class="tui-slider__track" aria-hidden="true"><span class="tui-slider__fill"></span><span class="tui-slider__thumb"></span></span><input type="range" min="0" max="100" value="${normalizedValue}" data-typography-role="body-l" aria-label="${escapeHtml(label)}" /></span><output data-typography-role="body-m">${normalizedValue}</output></label>`;
};
export const slider = ({ gallery = false, ...options } = {}) => {
  if (!gallery) return sliderState(options);
  return `<div class="tui-slider-gallery" data-runtime-component="slider"><div class="tui-slider-specimen" data-slider-style="style-1"><span class="tui-runtime-surface-label">样式 1 · 4px 背景条 / 16px 圆形把手</span>${sliderState({ ...options, variant: "style-1" })}</div><div class="tui-slider-specimen" data-slider-style="style-2"><span class="tui-runtime-surface-label">样式 2 · 20px 背景条 / 12px 圆形把手</span>${sliderState({ ...options, variant: "style-2" })}</div></div>`;
};
const colorPickerEyedropper = `<svg class="tui-color-picker__eyedropper-icon" viewBox="0 0 24 24" width="24" height="24" aria-hidden="true" focusable="false" data-icon-manual-fallback="color-picker/eyedropper" data-source="pixso"><path d="M12.7092 5.73192C12.187 5.20968 11.3402 5.20968 10.818 5.73192C10.2958 6.25416 10.2958 7.10088 10.818 7.62312L12.1787 8.98384L3.66864 17.4946C3.0485 18.1147 2.91928 19.0399 3.28102 19.7871L3.19584 19.8586C2.93472 20.1197 2.93472 20.543 3.19584 20.8042C3.45696 21.0653 3.88032 21.0653 4.14144 20.8042L4.21286 20.719C4.96012 21.0807 5.8853 20.9515 6.50544 20.3314L15.0155 11.8206L16.4916 13.2967C17.0138 13.819 17.8606 13.819 18.3828 13.2967C18.905 12.7745 18.905 11.9278 18.3828 11.4055L17.3798 10.4026L20.2166 7.56576C21.2611 6.52128 21.2611 4.82784 20.2166 3.78336C19.1722 2.73888 17.4787 2.73888 16.4342 3.78336L13.5974 6.62016L12.7092 5.73192ZM4.61398 18.4405L13.1241 9.92978L14.0697 10.8754L5.55958 19.3861C5.29846 19.6472 4.8751 19.6472 4.61398 19.3861C4.35286 19.125 4.35286 19.6472 4.61398 18.4405Z" fill="currentColor" /></svg>`;
const colorPickerTrack = (axis, label, value, max) => `<label class="tui-color-picker__field" data-axis="${axis}"><span class="tui-color-picker__field-label" data-typography-role="body-m">${label}</span><span class="tui-color-picker__track-row"><input class="tui-color-picker__track" type="range" min="0" max="${max}" value="${value}" aria-label="${label}" data-color-picker-axis="${axis}" /><output class="tui-color-picker__value" data-color-picker-value data-typography-role="body-s">${value}</output></span></label>`;
export const colorPicker = (options = {}) => {
  const disabled = Boolean(options.disabled);
  const hex = String(options.value ?? options.defaultValue ?? "FA2A2F").replace(/^#/, "").toUpperCase().replace(/[^0-9A-F]/g, "").slice(0, 6).padEnd(6, "0");
  const disabledAttr = disabled ? " disabled aria-disabled=\"true\"" : "";
  const favorites = ["E56224", "0000000C", "00000014", "0000001F", "00000029", "00000033", "0000003D", "00000047", "00000052", "0000005C", "00000066", "00000070", "0000007A", "00000085", "0000008F", "00000099", "000000A3"];
  return `<section class="tui-component tui-color-picker" ${attrs("color-picker", "ColorPicker/Tablet", "default", disabled ? "disabled" : "default", ` data-color-value="${hex}"${disabled ? " aria-disabled=\"true\"" : ""}`)} aria-label="颜色编辑器"><h3 class="tui-color-picker__title" data-slot="title" data-typography-role="title-s">Color Editor</h3><div class="tui-color-picker__tabs" role="tablist" aria-label="颜色模式"><button type="button" class="tui-color-picker__tab is-selected" role="tab" aria-selected="true" data-color-picker-tab="color-card"${disabledAttr}>Color card</button><button type="button" class="tui-color-picker__tab" role="tab" aria-selected="false" data-color-picker-tab="slider"${disabledAttr}>Slider</button><button type="button" class="tui-color-picker__tab" role="tab" aria-selected="false" data-color-picker-tab="color-disc"${disabledAttr}>Color disc</button></div><button type="button" class="tui-color-picker__mode" data-color-picker-mode aria-label="颜色模式：HSB"${disabledAttr}><span data-slot="mode" data-typography-role="body-l">HSB</span><span class="tui-color-picker__mode-icon" aria-hidden="true"></span></button><div class="tui-color-picker__controls">${colorPickerTrack("hue", "Hue", 360, 360)}${colorPickerTrack("saturation", "Saturation", 360, 360)}${colorPickerTrack("brightness", "Brightness", 360, 360)}${colorPickerTrack("alpha", "Alpha", 100, 100)}</div><div class="tui-color-picker__divider" role="separator"></div><div class="tui-color-picker__summary"><span class="tui-color-picker__summary-main"><span class="tui-color-picker__swatch" data-slot="preview" aria-label="当前颜色"></span><button type="button" class="tui-color-picker__eyedropper" data-slot="eyedropper" aria-label="吸取颜色"${disabledAttr}>${colorPickerEyedropper}</button></span><label class="tui-color-picker__hex" data-slot="hex"><span data-typography-role="body-s">Hex: #</span><input class="tui-color-picker__hex-input" type="text" value="${hex}" maxlength="6" inputmode="text" aria-label="Hex color" data-color-picker-hex${disabledAttr} /></label></div><div class="tui-color-picker__favorites" data-slot="favorites"><span class="tui-color-picker__favorites-label" data-typography-role="body-s">collect</span><div class="tui-color-picker__favorites-grid">${favorites.map((color, index) => index === 0 ? `<button type="button" class="tui-color-picker__favorite" data-color-value="${color}" aria-label="收藏色 ${color}" style="--tui-color-picker-swatch:var(--color-function-warning-100)"${disabledAttr}></button>` : index === 1 ? `<button type="button" class="tui-color-picker__favorite tui-color-picker__favorite--add" data-color-picker-add aria-label="添加收藏色"${disabledAttr}>+</button>` : `<button type="button" class="tui-color-picker__favorite" data-color-value="${color}" aria-label="收藏色 ${color}"${disabledAttr}></button>`).join("")}</div></div></section>`;
};
export const inputOtp = () => `<fieldset class="tui-component tui-input-otp" ${attrs("input-otp", "Input OTP/Default")}><legend data-typography-role="body-m">验证码</legend><div class="tui-input-otp__cells">${[1, 2, 3, 4, 5, 6].map((n) => `<input class="tui-input-otp__cell" type="text" inputmode="numeric" maxlength="1" aria-label="第 ${n} 位验证码" data-typography-role="body-l" />`).join("")}</div><small data-typography-role="body-s">请输入 6 位验证码</small></fieldset>`;
export const kbd = () => `<kbd class="tui-component tui-kbd" ${attrs("kbd", "Kbd/Default")} data-typography-role="body-m">⌘ K</kbd>`;

export const chart = () => `<figure class="tui-component tui-chart" ${attrs("chart", "Chart/Default")}><figcaption data-typography-role="title-s">项目趋势</figcaption><svg class="tui-chart__svg" viewBox="0 0 240 96" role="img" aria-label="项目趋势图" data-svg-role="chart"><path d="M8 78L52 58L96 64L140 32L184 42L232 14" fill="none" stroke="currentColor" stroke-width="1.5" /><path d="M8 80H232" fill="none" stroke="currentColor" stroke-width="1" opacity=".24" /></svg><span data-typography-role="body-s">本周完成度 84%</span></figure>`;
const calendarWeekdays = ["日", "一", "二", "三", "四", "五", "六"];
const calendarDays = ["26", "27", "28", "29", "30", "31", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "1", "2", "3", "4", "5"];
const calendarWeekMarkup = (className = "tui-calendar__week") => `<div class="${className}" data-typography-role="body-l">${calendarWeekdays.map((day) => `<span data-typography-role="body-l">${day}</span>`).join("")}</div>`;
const calendarDayMarkup = (className = "tui-calendar__days", selectedDay = "7") => `<div class="${className}" role="grid">${calendarDays.map((day, i) => `<button type="button" role="gridcell" class="${day === selectedDay && i === 12 ? "is-selected" : ""}" data-day="${day}" data-typography-role="body-l">${day}</button>`).join("")}</div>`;
export const calendar = ({ selectedDay = "7", className = "" } = {}) => `<section class="tui-component tui-calendar${className ? ` ${className}` : ""}" ${attrs("calendar", "Calendar/Default")}><header><button class="tui-icon-button tui-calendar__prev" type="button" aria-label="上个月">${icon("navigation/chevron-right", 20)}</button><strong data-typography-role="title-s">2026 年 08 月</strong><button class="tui-icon-button tui-calendar__next" type="button" aria-label="下个月">${icon("navigation/chevron-right", 20)}</button></header>${calendarWeekMarkup()}${calendarDayMarkup("tui-calendar__days", selectedDay)}</section>`;

const picker = (id, logicalName, label, value, iconName, panel) => `<div class="tui-component tui-picker" ${attrs(id, logicalName)}><label data-typography-role="body-m">${escapeHtml(label)}</label><button class="tui-picker__trigger" type="button" aria-haspopup="dialog" aria-expanded="false"><span data-slot="value" data-typography-role="body-l">${escapeHtml(value)}</span>${icon(iconName, 20)}</button><div class="tui-picker__panel" role="dialog" hidden>${panel}</div></div>`;
export const datePicker = () => picker("date-picker", "Date Picker/Default", "日期", "2026-08-07", "field/calendar", `${calendar({ className: "tui-calendar--embedded" })}<footer><button type="button" data-action="clear" data-typography-role="body-l">清除</button><button type="button" data-action="today" data-typography-role="body-l">今天</button></footer>`);
export const timePicker = () => picker("time-picker", "Time Picker/Default", "时间", "09:30", "field/clock", `<div class="tui-picker__columns"><div><span data-typography-role="body-s">时</span>${["08", "09", "10"].map((d) => `<button type="button" data-time-hour="${d}" data-typography-role="body-l" class="${d === "09" ? "is-selected" : ""}">${d}</button>`).join("")}</div><b data-typography-role="body-l">:</b><div><span data-typography-role="body-s">分</span>${["25", "30", "35"].map((d) => `<button type="button" data-time-minute="${d}" data-typography-role="body-l" class="${d === "30" ? "is-selected" : ""}">${d}</button>`).join("")}</div></div><footer><button type="button" data-action="clear" data-typography-role="body-l">清除</button><button type="button" data-action="confirm" data-typography-role="body-l">确定</button></footer>`);

const attachmentActions = ({ disabled = false } = {}) => `<span class="tui-attachment__actions" data-slot="actions"><button class="tui-icon-button tui-attachment__menu-trigger" data-slot="menu-trigger" type="button" aria-label="打开附件操作菜单" aria-haspopup="menu" aria-expanded="false"${disabled ? " disabled" : ""}>${icon("navigation/chevron-down", 20)}</button><div class="tui-button-dropdown__menu tui-attachment__menu" data-slot="menu" role="menu" hidden><button class="tui-button-dropdown__item" type="button" role="menuitem" data-action="preview" data-typography-role="body-l">预览</button><button class="tui-button-dropdown__item" type="button" role="menuitem" data-action="download" data-typography-role="body-l">下载</button></div></span>`;
export const attachment = (options = {}) => {
  const { items, ...single } = options;
  if (Array.isArray(items)) {
    return `<div class="tui-component tui-attachment-list" data-component="attachment" data-logical-component="Attachment/Default" data-variant="collection" data-state="default" data-framework="html" role="list">${items.map((item) => attachment(item)).join("")}</div>`;
  }
  const { type = "PDF", name = "项目说明.pdf", meta = "2.4 MB · 已上传", leading, content, actions, disabled = false } = single;
  return `<article class="tui-component tui-attachment" ${attrs("attachment", "Attachment/Default", "default", disabled ? "disabled" : "default")}${disabled ? " aria-disabled=\"true\"" : ""}>${slot(leading, `<span class="tui-attachment__type" data-slot="leading" data-typography-role="body-s">${escapeHtml(type)}</span>`)}${slot(content, `<div data-slot="content"><strong data-slot="title" data-typography-role="subtitle-s">${escapeHtml(name)}</strong><small data-slot="description" data-typography-role="body-s">${escapeHtml(meta)}</small></div>`)}${slot(actions, attachmentActions({ disabled }))}</article>`;
};
export const advancedHtmlComponents = {
  dialog, "alert-dialog": alertDialog, "semi-modal": semiModal,
  menubar, "context-menu": contextMenu, "dropdown-menu": dropdownMenu,
  popover, "hover-card": hoverCard, slider, "color-picker": colorPicker, "input-otp": inputOtp, kbd,
  chart, calendar, "date-picker": datePicker, "time-picker": timePicker,
  attachment
};
